### ISSUE TITLE
My footer is cut off onload

### ISSUE THREAD

**Issue by djjonbrown** [nelsW70/jenkins-for-da#2]
1039x703
<img width="1040" alt="screen shot 2018-07-01 at 9 16 29 am" src="https://user-images.githubusercontent.com/8303925/42134750-8cd5abf8-7d0f-11e8-94ad-246a1d7e1adb.png">

**Comment by nelsW70** [comment]
I have to take care of some stuff. Back later tonight and will take a look.

**Comment by nelsW70** [comment]
Try it now and see

**Comment by djjonbrown** [comment]
Fixed on Landscape tablet and taptop versions
